before_script:
  - export ANDROID_HOME="/opt/android-sdk-linux"
  - export JAVA_HOME="/home/ubuntu/.sdkman/candidates/java/current"

stages:
  - build

job1:
  stage: build
  script:
    - chmod 755 gradlew
    - ./gradlew build
  only:
    - development