before_script:
  - export ANDROID_HOME="/opt/android-sdk-linux"
  - export JAVA_HOME="/home/ubuntu/.sdkman/candidates/java/current"
  - export Version=$(cat app/build.gradle | grep "versionName" | grep -oE "[0-9]*\.[0-9]*\.[0-9]*")

stages:
  - build
  - testAndDoc
  - deploy

Build Package:
  stage: build
  script:
    - chmod 755 gradlew
    - ./gradlew assembleDebug --stacktrace

Test Source:
  stage: testAndDoc
  script:
    - chmod 755 gradlew
    - ./gradlew check

Generate Javadoc:
  stage: testAndDoc
  script:
    - chmod 755 gradlew
    - ./gradlew generateReleaseJavadoc
    - rm -rf /var/www/html/Documentation/*
    - cp -r javadoc/* /var/www/html/Documentation/

Deploy Package:
  stage: deploy
  script:
    - chmod 755 gradlew
    - ./gradlew assembleRelease
    - cp app/build/outputs/apk/app-release-unsigned.apk /var/www/html/Frontend_Android_App/wanderlust-app-${Version}-${CI_PIPELINE_ID}.apk
  only:
    - master