before_script:
  - export ANDROID_HOME="/opt/android-sdk-linux"
  - export JAVA_HOME="/home/ubuntu/.sdkman/candidates/java/current"
  - export Version=$(cat app/build.gradle | grep "versionName" | grep -oE "[0-9]*\.[0-9]*\.[0-9]*")

stages:
  - build
  - testAndDoc
  - deploy

Build Package:
  stage: build
  script:
    - chmod 755 gradlew
    - ./gradlew clean
    - ./gradlew assembleDebug --stacktrace

#Test Source:
#  stage: testAndDoc
#  script:
#    - sudo /etc/init.d/wanderlust-api stop
#    - echo "truncate table user; truncate table profile" | mysql -u root --password="X2E8BH5RLqwgnQ3L" wanderlust
#    - sudo /etc/init.d/wanderlust-api start
#    - sleep 6
#    - cat basic_database.sql | mysql -u root --password="X2E8BH5RLqwgnQ3L" wanderlust
#    - chmod 755 gradlew
#    - ./gradlew test
#    - ./gradlew connectedAndroidTest

Generate Javadoc:
  stage: testAndDoc
  script:
    - chmod 755 gradlew
    - ./gradlew generateReleaseJavadoc
    - rm -rf /var/www/html/Frontend_Android_App/Documentation/*
    - cp -r javadoc/* /var/www/html/Frontend_Android_App/Documentation/

Deploy Package:
  stage: deploy
  script:
    - chmod 755 gradlew
    - ./gradlew assembleRelease
    - app/build/outputs/apk/release/app-release.apk /var/www/html/Frontend_Android_App/wanderlust-app-${Version}-${CI_PIPELINE_ID}.apk
  only:
    - master