before_script:
  - export ANDROID_HOME="/opt/android-sdk-linux"
  - export JAVA_HOME="/home/ubuntu/.sdkman/candidates/java/current"

stages:
  - build
  - test

Build Package:
  stage: build
  script:
    - chmod 755 gradlew
    - ./gradlew assembleDebug --stacktrace
  only:
    - development

Test Source:
  stage: test
  script:
    - chmod 755 gradlew
    - ./gradlew check
  only:
    - development